version: 1
services:
  - type: web
    name: E-Commerce-Store
    env: node
    buildCommand: npm run build
    startCommand: npm start
    staticPublishPath: dist
    routes:
      - src: /*
        dest: /index.html
